### Creating DataFrames

In [1]:
import pandas as pd 
import numpy as np 

file_dir = "./P87-S2-Dataset-Basics-Resources/"

In [3]:
data = np.random.random(size=(5,3))
print(data)
df = pd.DataFrame(data=data, columns=["A", "B", "C"])

df

[[0.93066976 0.15450837 0.47496532]
 [0.08966814 0.87447445 0.17657516]
 [0.84085539 0.33522662 0.12893258]
 [0.34807179 0.35541736 0.9589612 ]
 [0.20416297 0.62299069 0.15235031]]


A         B         C
0  0.930670  0.154508  0.474965
1  0.089668  0.874474  0.176575
2  0.840855  0.335227  0.128933
3  0.348072  0.355417  0.958961
4  0.204163  0.622991  0.152350

In [4]:
df = pd.DataFrame(data={"A": [1,2,3], "B": ['Sam', 'Alex', 'John']})

df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [10]:
dtype = [("A", int), ("B", (str, 20))]
data = np.array([(1, "Sam"), (2, "Alex"), (3, "John")], dtype=dtype)

df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John

### Saving and Serialising a dataframe

In [11]:
df = pd.DataFrame(np.random.random(size=(100000, 4)), columns=["A", "B", "C", "D"])

df.head()

A         B         C         D
0  0.379920  0.434402  0.537697  0.103735
1  0.406891  0.409102  0.489950  0.904801
2  0.024077  0.060613  0.236212  0.555531
3  0.394593  0.790248  0.411609  0.107437
4  0.858013  0.045608  0.390434  0.494062

In [13]:
df.to_csv("save.csv", index=False, float_format="%0.4f")

In [14]:
df.to_pickle("save.pkl")

In [15]:
df.to_hdf("save.hdf", key="data", format="table")

In [17]:
df  = pd.read_csv(file_dir + "astronauts.csv")

In [19]:
df.tail()

Name    Year  Group   Status Birth Date  \
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
352               4044            7              41.0   
353                  0            0               0.0   
354                295            1               0.5   
355                835            3              20.0   
356                692            0               0.0   

                                              Missions Death Date  \
352  STS-58 (Columbia). STS-86/89 (Atlantis/Endeavo...        NaN   
353                                                NaN        NaN   
354                                          Apollo 15        NaN   
355  Gemini 3, Gemini 10, Apollo 10, Apollo 16, STS...        NaN   
356            STS-120 (Discovery), STS-130 (Endeavor)        NaN   

    Death Mission  
352           NaN  
353           NaN  
354           NaN  
355           NaN  
356           NaN

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Name                 357 non-null    object 
 1   Year                 330 non-null    float64
 2   Group                330 non-null    float64
 3   Status               357 non-null    object 
 4   Birth Date           357 non-null    object 
 5   Birth Place          357 non-null    object 
 6   Gender               357 non-null    object 
 7   Alma Mater           356 non-null    object 
 8   Undergraduate Major  335 non-null    object 
 9   Graduate Major       298 non-null    object 
 10  Military Rank        207 non-null    object 
 11  Military Branch      211 non-null    object 
 12  Space Flights        357 non-null    int64  
 13  Space Flight (hr)    357 non-null    int64  
 14  Space Walks          357 non-null    int64  
 15  Space Walks (hr)     357 non-null    flo

In [21]:
df.describe()

Year       Group  Space Flights  Space Flight (hr)  Space Walks  \
count   330.000000  330.000000     357.000000         357.000000   357.000000   
mean   1985.106061   11.409091       2.364146        1249.266106     1.246499   
std      13.216147    5.149962       1.428700        1896.759857     2.056989   
min    1959.000000    1.000000       0.000000           0.000000     0.000000   
25%    1978.000000    8.000000       1.000000         289.000000     0.000000   
50%    1987.000000   12.000000       2.000000         590.000000     0.000000   
75%    1996.000000   16.000000       3.000000        1045.000000     2.000000   
max    2009.000000   20.000000       7.000000       12818.000000    10.000000   

       Space Walks (hr)  
count        357.000000  
mean           7.707283  
std           13.367973  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%           12.000000  
max           67.000000

In [22]:
df.corr()

Year     Group  Space Flights  Space Flight (hr)  \
Year               1.000000  0.980934       0.036420           0.331386   
Group              0.980934  1.000000      -0.011386           0.325683   
Space Flights      0.036420 -0.011386       1.000000           0.325233   
Space Flight (hr)  0.331386  0.325683       0.325233           1.000000   
Space Walks        0.210073  0.217891       0.257073           0.472796   
Space Walks (hr)   0.253502  0.261384       0.258642           0.454408   

                   Space Walks  Space Walks (hr)  
Year                  0.210073          0.253502  
Group                 0.217891          0.261384  
Space Flights         0.257073          0.258642  
Space Flight (hr)     0.472796          0.454408  
Space Walks           1.000000          0.985755  
Space Walks (hr)      0.985755          1.000000

In [25]:
df["Year"].value_counts()

1996.0    35
1978.0    35
1998.0    25
1990.0    23
1966.0    19
1995.0    19
1992.0    19
1980.0    19
1984.0    18
2000.0    17
1987.0    15
1963.0    14
1985.0    13
2004.0    11
1967.0    11
2009.0     9
1962.0     8
1959.0     7
1969.0     7
1965.0     6
Name: Year, dtype: int64

In [26]:
df.max()

Name                 Yvonne D. Cagle
Year                          2009.0
Group                           20.0
Status                       Retired
Birth Date                  9/9/1952
Birth Place              Yonkers, NY
Gender                          Male
Space Flights                      7
Space Flight (hr)              12818
Space Walks                       10
Space Walks (hr)                67.0
dtype: object